-- MySQL Script generated by MySQL Workbench
-- Sun Jun 18 14:45:45 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema clinica_medica
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `clinica_medica` ;

-- -----------------------------------------------------
-- Schema clinica_medica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `clinica_medica` DEFAULT CHARACTER SET utf8 ;
USE `clinica_medica` ;

-- -----------------------------------------------------
-- Table `clinica_medica`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_medica`.`endereco` (
  `id` INT NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_medica`.`atendente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_medica`.`atendente` (
  `matricula` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `formacao` VARCHAR(100) NOT NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC),
  INDEX `fk_atendente_endereco_idx` (`endereco_id` ASC),
  CONSTRAINT `fk_atendente_endereco`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `clinica_medica`.`endereco` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_medica`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_medica`.`paciente` (
  `cpf` VARCHAR(20) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  INDEX `fk_paciente_endereco1_idx` (`endereco_id` ASC),
  CONSTRAINT `fk_paciente_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `clinica_medica`.`endereco` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_medica`.`consultorio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_medica`.`consultorio` (
  `numero` INT NOT NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`numero`),
  INDEX `fk_consultorio_endereco1_idx` (`endereco_id` ASC),
  CONSTRAINT `fk_consultorio_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `clinica_medica`.`endereco` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_medica`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_medica`.`medico` (
  `crm` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `especialidade` VARCHAR(100) NOT NULL,
  `consultorio_numero` INT NOT NULL,
  `endereco_id` INT NOT NULL,
  PRIMARY KEY (`crm`),
  UNIQUE INDEX `crm_UNIQUE` (`crm` ASC),
  INDEX `fk_medico_endereco1_idx` (`endereco_id` ASC),
  INDEX `fk_medico_consultorio1_idx` (`consultorio_numero` ASC),
  CONSTRAINT `fk_medico_endereco1`
    FOREIGN KEY (`endereco_id`)
    REFERENCES `clinica_medica`.`endereco` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_medico_consultorio1`
    FOREIGN KEY (`consultorio_numero`)
    REFERENCES `clinica_medica`.`consultorio` (`numero`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `clinica_medica`.`consulta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `clinica_medica`.`consulta` (
  `numero` INT NOT NULL,
  `data` DATE NOT NULL,
  `horario` TIME NOT NULL,
  `paciente_cpf` VARCHAR(20) NOT NULL,
  `medico_crm` VARCHAR(11) NOT NULL,
  `atendente_matricula` INT NOT NULL,
  PRIMARY KEY (`numero`, `paciente_cpf`, `medico_crm`, `atendente_matricula`),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC),
  INDEX `fk_consulta_paciente1_idx` (`paciente_cpf` ASC),
  INDEX `fk_consulta_medico1_idx` (`medico_crm` ASC),
  INDEX `fk_consulta_atendente1_idx` (`atendente_matricula` ASC),
  CONSTRAINT `fk_consulta_paciente1`
    FOREIGN KEY (`paciente_cpf`)
    REFERENCES `clinica_medica`.`paciente` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_consulta_medico1`
    FOREIGN KEY (`medico_crm`)
    REFERENCES `clinica_medica`.`medico` (`crm`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_consulta_atendente1`
    FOREIGN KEY (`atendente_matricula`)
    REFERENCES `clinica_medica`.`atendente` (`matricula`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
